name: Bug Report
description: Report a bug to help us improve Gor
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of Gor
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true

  - type: input
    id: gor-version
    attributes:
      label: Gor Version
      description: What version of Gor are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: "e.g., 1.21.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - FreeBSD
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Create file '...'
        3. Execute '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, include error messages
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal Reproduction Example
      description: Provide a minimal code example that demonstrates the issue
      render: go
      placeholder: |
        package main

        import "github.com/cuemby/gor/pkg/gor"

        func main() {
            // Your minimal example here
        }

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Stack Trace
      description: Relevant error logs, stack traces, or debug output
      render: text
      placeholder: Paste any relevant logs here

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - Database: SQLite/PostgreSQL/MySQL
        - Container: Docker/Podman
        - Cloud provider: AWS/GCP/Azure
        - Any other relevant details

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Any temporary workaround you've found (optional)
      placeholder: Describe any workarounds you've discovered

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical (application crashes, data loss)
        - High (major functionality broken)
        - Medium (functionality partially broken)
        - Low (minor issue, cosmetic)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute a fix?
      options:
        - label: I would like to work on fixing this bug
        - label: I can provide additional testing
        - label: I can help with documentation updates