name: Feature Request
description: Suggest a new feature or enhancement for Gor
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the roadmap and documentation
          required: true
        - label: This feature aligns with Gor's philosophy and goals
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Clearly describe the problem or limitation you're experiencing.
        Include specific use cases and scenarios where this feature would be helpful.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Explain how you envision this feature working.
        Include API design, user interface changes, or workflow improvements.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternative solutions have you considered?
      placeholder: |
        Describe any alternative approaches you've considered.
        Explain why the proposed solution is better than alternatives.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of Gor does this feature relate to?
      options:
        - Core Framework
        - CLI Tool
        - ORM/Database
        - Authentication
        - Caching System
        - Queue System
        - Real-time (Cable)
        - Testing Framework
        - Documentation
        - Development Tools
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (significantly improves workflow)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be valuable
      placeholder: |
        1. Use case: As a developer building a real-time chat app...
        2. Use case: When deploying to production...
        3. Use case: During development workflow...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: Proposed API or interface design
      render: go
      placeholder: |
        // Example API design
        type NewFeature interface {
            DoSomething(ctx context.Context, param string) error
        }

        // Usage example
        app.NewFeature().DoSomething(ctx, "example")

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Show how this feature would be used
      render: go
      placeholder: |
        // Before (current limitations)
        // ...

        // After (with proposed feature)
        // ...

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Impact
      description: How would this feature affect documentation?
      placeholder: |
        - New sections needed in documentation
        - Examples to be added
        - Migration guides required
        - API reference updates

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check all that apply
      options:
        - label: This feature requires breaking changes
        - label: This feature affects performance
        - label: This feature requires new dependencies
        - label: This feature affects security
        - label: This feature requires database migrations
        - label: This feature affects backwards compatibility

  - type: textarea
    id: testing
    attributes:
      label: Testing Strategy
      description: How should this feature be tested?
      placeholder: |
        - Unit tests for core functionality
        - Integration tests for end-to-end workflows
        - Performance benchmarks
        - Example applications demonstrating usage

  - type: dropdown
    id: rails-inspiration
    attributes:
      label: Rails Inspiration
      description: Is this feature inspired by Ruby on Rails?
      options:
        - "Yes - direct Rails equivalent"
        - "Yes - Rails-inspired adaptation"
        - "No - Go-specific feature"
        - "No - novel functionality"

  - type: textarea
    id: rails-reference
    attributes:
      label: Rails Reference (if applicable)
      description: Reference to equivalent Rails functionality
      placeholder: |
        Link to Rails documentation or describe the Rails feature this is based on.
        Explain how the Go implementation would differ or improve upon Rails.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I would like to implement this feature
        - label: I can help with design and planning
        - label: I can provide testing and feedback
        - label: I can help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: |
        Add any other context about the feature request here.
        Include links to relevant resources, screenshots, or references.