name: SLSA Generic Generator

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build artifacts
      run: |
        # Build for multiple platforms
        mkdir -p dist

        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -o dist/gor-linux-amd64 ./cmd/gor

        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -o dist/gor-linux-arm64 ./cmd/gor

        # Darwin amd64
        GOOS=darwin GOARCH=amd64 go build -o dist/gor-darwin-amd64 ./cmd/gor

        # Darwin arm64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -o dist/gor-darwin-arm64 ./cmd/gor

        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -o dist/gor-windows-amd64.exe ./cmd/gor

    - name: Generate hashes
      shell: bash
      id: hash
      run: |
        cd dist
        echo "hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gor-binaries
        path: dist/
        if-no-files-found: error
        retention-days: 5

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    # Use the generic generator to generate provenance.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true

  verification:
    needs: [build, provenance]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: gor-binaries

    - name: Download provenance
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.provenance.outputs.provenance-name }}

    - name: Install SLSA verifier
      uses: slsa-framework/slsa-verifier/actions/installer@v2.5.1

    - name: Verify assets
      run: |
        slsa-verifier verify-artifact \
          --provenance-path ${{ needs.provenance.outputs.provenance-name }} \
          --source-uri github.com/cuemby/gor \
          gor-linux-amd64 \
          gor-linux-arm64 \
          gor-darwin-amd64 \
          gor-darwin-arm64 \
          gor-windows-amd64.exe